### ISSUE TITLE
建议乐观锁的支持半自动化生效方式

### ISSUE THREAD

**Issue by breaksilence** [Dreamroute/locker#22]
目前现有的配置模式是所有update都会进行乐观锁处理，不需要乐观锁的配置VersionLocker注解为false，如果我仅仅需要小部分的update进行乐观锁控制，那么我需要将所有的非乐观锁的update全部标记为false，不知道是否理解有偏差，如果没有偏差，我建议增加另一种模式：当配置乐观锁为true时进行乐观锁拦截处理，否则不进行处理

**Comment by Dreamroute** [comment]
你的理解是很正确的，你把源码里面的默认为true改成false，就变成你需要的那种方式了
