### ISSUE TITLE
VersionLockerResolver的静态初始化方法，获取本类方法的名字写错了，后面的小伙伴们注意了

### ISSUE THREAD

**Issue by lianyuteng** [Dreamroute/locker#28]
下楼放图

**Comment by lianyuteng** [comment]
![image](https://user-images.githubusercontent.com/20927567/44705207-8a98f680-aad0-11e8-9f4d-c8b2d1fa9ff3.png)

**Comment by lianyuteng** [comment]
这是个问题啊楼主

**Comment by Dreamroute** [comment]
@lianyuteng omg，已改，谢谢指出，近期正在重构此插件，目的：兼容最新mybatis版本，兼容性升级至JDK1.8

**Comment by Dreamroute** [comment]
@lianyuteng 近期会做#27列表的优化，后续更加人性化
